---
- name: HAProxy defaults
  template: src=etc/default/haproxy dest=/etc/default/haproxy
  notify: reload haproxy

- name: install haproxy
  apt: pkg=haproxy

# WORKAROUND: `service haproxy stop` fails due to incorrect `start-stop-daemon --pid`
- name: fix haproxy init script
  template: src=etc/init.d/haproxy dest=/etc/init.d/haproxy mode=0755

- name: install ssl cert+key
  template: src=etc/haproxy/openstack.pem dest=/etc/haproxy/openstack.pem
            owner=haproxy group=haproxy mode=0600
  notify: reload haproxy
  tags:
    - ssl

- name: haproxy config
  template: src=etc/haproxy/haproxy_{{ haproxy_type }}.cfg
            dest=/etc/haproxy/haproxy.cfg mode=0644
  notify: reload haproxy

- meta: flush_handlers

- name: start and enable haproxy
  service: name=haproxy state=started enabled=yes

- include: monitoring.yml tags=monitoring,common
