---
- name: restart neutron services
  service: name={{ item }} state=restarted_if_running must_exist=false
  when: restart|default('True')
  with_items:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-openvswitch-agent
    - neutron-linuxbridge-agent
