---
ironic:
  virtualenv: /opt/stack/ironic
  path: /opt/stack/ironic
  client_rev: e611ae5f206d846e72684ba16c345653232c45c3
  client_virtualenv: /opt/stack/python-ironicclient
  client_path: /opt/stack/python-ironicclient
  tftp_server: hostvars[inventory_hostname][primary_interface]['ipv4']['address']
  dns_server: hostvars[inventory_hostname][primary_interface]['ipv4']['address']
  api_url:
    scheme: http
    host: hostvars[inventory_hostname][primary_interface]['ipv4']['address']
    port: 6385
  tftpboot_path: /tftpboot
  enabled_drivers:
    - fake
    - pxe_ssh
    - pxe_ipmitool

  source:
    rev: '53171f75a64a26dcec91facbdec95b2ed7f74338'
  package:
    console_scripts:
      - ironic-api
      - ironic-conductor
      - ironic-dbsync
      - ironic-nova-bm-migrate
      - ironic-rootwrap

  package:
    console_scripts:
      - ironic-api
      - ironic-conductor
      - ironic-dbsync
      - ironic-nova-bm-migrate
      - ironic-rootwrap

  logs:
    - paths:
        - /var/log/ironic/ironic-api.log
      fields:
        type: openstack
        tags: ironic,ironic-api
    - paths:
        - /var/log/ironic/ironic-conductor.log
      fields:
        type: openstack
        tags: ironic,ironic-conductor
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
