---
- name: controller 0 hosts file
  hosts: controller[0]
  vars_files:
  - ../vars/main.yml
  tasks:
    - name: add controller node to /etc/hosts
      lineinfile: dest=/etc/hosts regexp={{ testenv_instance_names[0] }}
                  insertafter=EOF
                  line="127.0.1.1 {{ testenv_instance_names[0] }}"

- name: controller 1 hosts file
  hosts: controller[1]
  vars_files:
  - ../vars/main.yml
  tasks:
    - name: add controller node to /etc/hosts
      lineinfile: dest=/etc/hosts regexp={{ testenv_instance_names[1] }}
                  insertafter=EOF
                  line="127.0.1.1 {{ testenv_instance_names[1] }}"

- name: compute hosts file
  hosts: compute
  vars_files:
  - ../vars/main.yml
  tasks:
    - name: add compute node to /etc/hosts
      lineinfile: dest=/etc/hosts regexp={{ testenv_instance_names[2] }}
                  insertafter=EOF
                  line="127.0.1.1 {{ testenv_instance_names[2] }}"

- name: tasks for all
  hosts: all
  serial: 10
  tasks:
  # Set Locale
  - name: Generate en_US locale
    command: /usr/sbin/locale-gen en_US

  - name: set locale to en_US
    command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

  - include: ../../../roles/common/tasks/proxy.yml

  - name: add pip
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: python-pip

  - name: get backports.ssl_match_hostname for apt repo installs
    pip:
      name: backports.ssl_match_hostname

  - name: Add BlueBox OpenStack PPA
    apt_repository: repo='ppa:blueboxgroup/openstack'

  # don't run this on existing clusters
  - name: Run a full dist-upgrade
    apt: update_cache=yes cache_valid_time=3600 upgrade=dist

  - name: Ubuntu 14.04 style /etc/network/interfaces.d/ directory
    file: dest=/etc/network/interfaces.d state=directory owner=root
          group=root mode=0755

  - name: /etc/network/interfaces to support interfaces.d/
    template: src=../templates/etc/network/interfaces
              dest=/etc/network/interfaces

  - name: default interfaces.d/eth0.cfg
    template: src=../templates/etc/network/interfaces.d/eth0.cfg
              dest=/etc/network/interfaces.d/eth0.cfg

- name: network tasks
  hosts: network
  tasks:
  - name: interfaces.d/eth0.cfg with NAT for floating IP pool
    template: src=../templates/etc/network/interfaces.d/eth0-controllers.cfg
              dest=/etc/network/interfaces.d/eth0.cfg
    notify: bounce eth0

  handlers:
  - name: bounce eth0
    shell: ifdown eth0; ifup eth0

- name: compute and network tasks
  hosts: network:compute
  serial: 10
  tasks:
  - name: Upgrade kernel to support VXLAN
    apt: pkg={{ item }}
    with_items:
      - linux-generic-lts-trusty
      - linux-tools-lts-trusty
    when: neutron.plugin == 'ml2'
    notify: restart machine

  - include: ../../../roles/common/tasks/noproxy.yml

  - meta: flush_handlers

  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} port=22 state=started
    sudo: false

  handlers:
  - name: restart machine
    command: shutdown -r now
    async: 0
    poll: 0
    failed_when: False
