---
- name: nova process checks
  sensu_process_check: service={{ item }}
  with_items:
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
  notify: restart sensu-client

- name: nova-api process checks
  sensu_process_check: service=nova-api warn_over=20 crit_over=30
  notify: restart sensu-client

- name: nova-api check
  sensu_check: name=check-nova-api plugin=check-os-api.rb
               args="--service nova"
  notify: restart sensu-client

- name: nova-services check
  sensu_check: name=check-nova-services plugin=check-nova-services.sh
               use_sudo=true
  notify: restart sensu-client

- name: nova metrics check
  sensu_metrics_check: name=nova-metrics plugin=metrics-nova.py
                       args='--scheme {{ monitoring.graphite.cluster_prefix }}.nova.hypervisor'
                       interval=3600
  notify: restart sensu-client

- name: nova state metrics check
  sensu_metrics_check: name=nova-state-metrics plugin=metrics-nova-state.py
                       args='--scheme {{ monitoring.graphite.cluster_prefix }}.nova.states'
                       interval=3600
  notify: restart sensu-client

- name: nova oversubscribe metrics check
  sensu_metrics_check: name=nova-oversubscribe-metrics plugin=metrics-nova-oversub.sh
                       args='-s {{ monitoring.graphite.cluster_prefix }}.nova.oversubscription'
                       interval=3600
  notify: restart sensu-client

- name: nova metrics
  template: src=etc/collectd/plugins/nova.conf dest=/etc/collectd/plugins/nova.conf
  notify: restart collectd
  when: collectd is defined and collectd.enabled|bool
  tags: collectd
