---
dependencies:
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.erlang.repo }} {{ ansible_lsb.codename }} contrib'
        key_url: '{{ apt_repos.erlang.key_url }}'
      - repo: 'deb {{ apt_repos.rabbitmq.repo }} testing main'
        key_url: '{{ apt_repos.rabbitmq.key_url }}'
  - role: monitoring-common
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
