---
rabbitmq:
  cluster: False
  erlang_cookie: 6IMgelGs3Ygu
  user: openstack
  nodename: 'rabbit@{{ ansible_hostname }}'
  ip: '0.0.0.0'
  port: 5672
  management_port: 15672
  admin_cli_url: 'http://localhost:15672/cli/rabbitmqadmin'
