---
- name: default images
  glance_image: name={{ item.name }}
                copy_from={{ item.url }}
                container_format=bare
                disk_format=qcow2
                auth_url={{ endpoints.auth_uri }}
                login_tenant_name=admin
                login_username=provider_admin
                login_password={{ secrets.provider_admin_password }}
                is_public=yes
                timeout=12000
  with_items: glance.images
  run_once: true
