---
- name: keystone services
  keystone_service: name={{ item.name }}
                    type={{ item.type }}
                    description='{{ item.description }}'
                    public_url={{ item.public_url }}
                    internal_url={{ item.internal_url }}
                    admin_url={{ item.admin_url }}
                    region=RegionOne
                    auth_url={{ endpoints.auth_uri }}
                    tenant_name=admin
                    login_user=provider_admin
                    login_password={{ secrets.provider_admin_password }}
  with_items: keystone.services
  when: endpoints[item.name] is defined and endpoints[item.name]
  run_once: true
