---
- name: install apache
  apt: pkg={{ item }}
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: lesscpy must be in apache PATH
  pip: name=lesscpy version=0.9j

- name: disable apache status
  command: a2dismod status
  notify:
    - restart apache

- name: create horizon config directory
  file: dest=/etc/openstack-dashboard state=directory

- name: apache ports config
  template: src=etc/apache2/ports.conf
            dest=/etc/apache2/ports.conf
  notify:
    - restart apache

- name: disable default apache site
  command: a2dissite 000-default
  notify:
    - restart apache

- name: create horizon config directory
  file: dest=/etc/openstack-dashboard state=directory

- name: openstack dashboard config (12.04)
  template: src=etc/apache2/sites-available/openstack_dashboard.conf
            dest=/etc/apache2/sites-available/openstack_dashboard
  when: ansible_distribution_version == "12.04"
  notify:
    - restart apache

- name: openstack dashboard config
  template: src=etc/apache2/sites-available/openstack_dashboard.conf
            dest=/etc/apache2/sites-available/openstack_dashboard.conf
  when: ansible_distribution_version != "12.04"
  notify:
    - restart apache

- name: enable horizon apache site
  command: a2ensite openstack_dashboard
  notify:
    - restart apache

- name: horizon local settings
  template: src=etc/openstack-dashboard/{{ item }}
            dest=/etc/openstack-dashboard/{{ item }}
            mode=0644
  with_items:
    - local_settings.py
    - __init__.py
  notify:
    - restart apache

- name: create static assets directory
  file: dest="{{ 'horizon'|ursula_package_path(openstack_package_version) }}/static"
        owner=www-data group=www-data state=directory
  when: openstack_install_method == 'package'

- name: create static assets directory
  file: dest="/opt/stack/horizon/static"
        owner=www-data group=www-data state=directory
  when: openstack_install_method == 'source'

- name: create customer-specific static assets directories
  file: dest=/etc/openstack-dashboard/{{ item }} state=directory
  with_items:
    - static
    - static/dashboard
    - static/dashboard/img
    - static/dashboard/fonts

- name: custom horizon logo
  get_url: url={{ item.url }}
           dest=/etc/openstack-dashboard/static/dashboard/{{ item.name }}
  with_items:
    - { name: img/logo.png, url: "{{ horizon.logo_url }}"  }
    - { name: img/logo-splash.png, url: "{{ horizon.logo_url }}" }
    - { name: img/favicon.ico, url: "{{ horizon.favicon_url }}" }

- name: gather static assets from openstack package install
  environment:
    DJANGO_SETTINGS_MODULE: 'openstack_dashboard.settings'
    PYTHONPATH: /etc/openstack-dashboard:$PYTHONPATH
  shell: "{{ item }}"
  with_items:
    - "{{ 'horizon'|ursula_package_path(openstack_package_version) }}/bin/django-admin.py collectstatic --noinput"
    - "{{ 'horizon'|ursula_package_path(openstack_package_version) }}/bin/django-admin.py compress"
  when: openstack_install_method == 'package'

- name: gather static assets from openstack source install
  environment:
    DJANGO_SETTINGS_MODULE: 'openstack_dashboard.settings'
    PYTHONPATH: "/etc/openstack-dashboard:{{ horizon.virtualenv }}/../:$PYTHONPATH"
  shell: "{{ item }}"
  with_items:
    - "{{ horizon.virtualenv }}/bin/django-admin.py collectstatic --noinput"
    - "{{ horizon.virtualenv }}/bin/django-admin.py compress"
  when: openstack_install_method == 'source'

- name: ensure apache started
  service: name=apache2 state=started

- name: Permit HTTP and HTTPS
  ufw: rule=allow to_port={{ item }} proto=tcp
  with_items:
  - 80
  - 443

- include: monitoring.yml tags=monitoring,common
