---
dependencies:
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.cloud_archive.repo }} precise-updates/icehouse main'
        key_package: ubuntu-cloud-keyring
    when: ansible_distribution_version == "12.04"
  - role: monitoring-common
  - role: logging-config
    service: nova
    logdata: "{{ nova.logs }}"
  - role: openstack-source
    project_name: nova
    project_rev: "{{ nova.source.rev }}"
    git_mirror: "{{ nova.source.git_mirror }}"
    rootwrap: True
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: nova
    rootwrap: True
    package_alternatives: "{{ nova.package.console_scripts }}"
    when: openstack_install_method == 'package'
